# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [1]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [2]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)

# 1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
print(f'[1] Shape of nparr: {nparr.shape}\n\
    Dimensions of nparr: {nparr.ndim}\n\
    Type of elements in nparr: {nparr.dtype}\n\
')

# 2. Determine the standard deviation of all elements in `nparr`
print(f'[2] Standard deviation of nparr: {nparr.std():.2f}\n')

# 3. Determine the position (not the value) of the maximum value element in `nparr`
print(f'[3] Index of max val in nparr [row-index, col-index]: {[i[0] for i in np.where(nparr == nparr.max())]}\n')

# 4. Create an array of the same shape as `nparr` but filled with zeros
nparr_zero = np.zeros(nparr.shape)
print(f'[4] Zero-Array with shape of nparr:\n{nparr_zero}\n')

# 5. Create an array of the same shape as `nparr` but filled with ones
nparr_identity = np.ones_like(nparr)
print(f'[5] Identity-Array with shape of nparr:\n{nparr_identity}\n')

# 6. Create an array of the same shape as `nparr` but where all elements are the square root values
nparr_sqrt = np.sqrt(nparr)
print(f'[6] Array with sqare root vals:\n{nparr_sqrt}\n')

# 7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`
nparr_dot_nparrT = nparr.dot(nparr.T)
print(f'[7] nparr dot nparrT:\n{nparr_dot_nparrT}\n')

[1] Shape of nparr: (12, 6)
    Dimensions of nparr: 2
    Type of elements in nparr: int32

[2] Standard deviation of nparr: 20.78

[3] Index of max val in nparr [row-index, col-index]: [11, 5]

[4] Zero-Array with shape of nparr:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[5] Identity-Array with shape of nparr:
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[6] Array with sqare root vals:
[[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.64911064 12.68857754 12.72792206]
 [12.76714533 12.80624847 12.845232

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [3]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)

# 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000`
print(f'[1] Row with traffic vals > 10,000: {len(a_df.loc[a_df["cnt"] > 10_000]):,}\n')

# 2. Print the names of all the columns of the dataframe
print(f'[2] Column names of a_df dataframe: {a_df.columns.values}\n')

# 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
print(f'[3] 10th and 3rd row of a_df dataframe:\n{a_df.iloc[[10 - 1, 3 - 1]]}\n')

# 4. Which US `state` has the `8th` largest total airport traffic? Please, make sure you use the correct variable as described above.
print(f'[4] State with 8th highest total traffic: {(a_df.groupby("state")["cnt"].sum()).nlargest(8)[[-1]].index[0]}\n')

# 5. Which state has the second-most total number of airports (i.e. the second-most amount of airports)?
print(f'[5] State with 2nd highest total no. of airports: {a_df["state"].value_counts().nlargest(2)[[-1]].index[0]}\n')

# 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?

# Creating a subset with aggregate functions to count the number of  size and sum
airports_traffic_by_city = a_df.groupby('city').agg(
    tot_airports=('city', 'size'),
    tot_traffic=('cnt', 'sum')
)
# To find the city with minimum traffic out of all the cities that have more than 1 airports in it.

airport_city_traffice_least = airports_traffic_by_city.loc[airports_traffic_by_city['tot_airports'] > 1].idxmin()['tot_traffic']
print(f'[6] City with total airport traffic which has least is : {airport_city_traffice_least}')

# 7. What is the total airport traffic for all states that border the state of Massachusetts?
# States bordering Massachusetts(Ref: https://thefactfile.org/u-s-states-and-their-border-states/)
states_bordering_MA_tot = a_df.loc[a_df['state'].isin(['NY', 'RI', 'VT','CT', 'NH',])]['cnt'].sum()
print(f'[7] Total traffic for all states bordering Massachusetts: {states_bordering_MA_tot:,}')

[1] Row with traffic vals > 10,000: 10

[2] Column names of a_df dataframe: ['iata' 'airport' 'city' 'state' 'country' 'lat' 'long' 'cnt']

[3] 10th and 3rd row of a_df dataframe:
  iata                          airport               city state country  \
9  CLT  Charlotte/Douglas International          Charlotte    NC     USA   
2  DFW  Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
9  35.214011 -80.943126  10490  
2  32.895951 -97.037200  20662  

[4] State with 8th highest total traffic: CO

[5] State with 2nd highest total no. of airports: TX

[6] City with total airport traffic which has least is : Charleston
[7] Total traffic for all states bordering Massachusetts: 22,007
